# -----------------------------------------------------------------------
"""
Variable containing the base list of commands that don't require user input
"""
template = [
	'vtp mode transparent',
	'no service pad',
	'service tcp-keepalives-in',
	'service tcp-keepalives-out',
	'service timestamps debug datetime msec localtime',
	'service timestamps log datetime msec localtime',
	'service password-encryption',
	'no snmp-server community public RO',
	'no snmp-server community private RW',
	'no ip http server',
	'no ip http secure-server',
	'sip dhcp bootp ignore',
	'cdp run',
	'lldp run',
	'boot-start-marker',
	'boot-end-marker',
	'logging buffered 65536 debugging',
	'no logging console',
	'no logging monitor',
	'no ip domain-lookup',
	'spanning-tree mode rapid-pvst',
	'spanning-tree portfast default',
	'spanning-tree portfast bpduguard default',
	'spanning-tree loopguard default',
	'errdisable recovery cause all',
	'errdisable recovery interval 60',
	'line con 0',
	' login local',
	' logging synchronous',
	'line vty 0 4',
	' login local',
	' transport input ssh',
	' logging synchronous',
	'line vty 5 15',
	' login local',
	' transport input ssh',
	' logging synchronous',
	'ip ssh version 2',
	'crypto key gen rsa mod 2048',
	'wr mem',
]
# -----------------------------------------------------------------------